name: TravelConcierge
options:
  bundleIdPrefix: com.travelconcierge
configs:
  Debug: debug
  Release: release
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    SWIFT_VERSION: "5.0"
targets:
  TravelConcierge:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: TravelConcierge
    info:
      path: TravelConcierge/Info.plist
      properties:
        CFBundleDisplayName: TravelConcierge
        CFBundleIdentifier: com.travelconcierge.app
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIUserInterfaceStyle: Automatic
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.travelconcierge.app
        SWIFT_VERSION: "5.0"
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor 